try{
    console.log("hello")
    console.log(a)
} catch(error){
    console.log("handled", error)
}

// same code without try catch

    // console.log("hello")
    // console.log(a)
    // console.log("end")

    